// This file isn't generated, but this comment is necessary to exclude it from analysis.
// <auto-generated/>

using System.Collections.Generic;
using System.Linq;

namespace QualityAssurance.Scripts
{
	internal static class ScriptsPreserve
	{
		[System.AttributeUsage(System.AttributeTargets.All)]
		private sealed class PreserveAttribute : System.Attribute
		{
			public bool AllMembers;
			public bool Conditional;
		}

		[Preserve]
		private static void SkipCodeFromBeingLinked()
		{
			Enumerable.LastOrDefault(new List<int>(), i => true);
		}
	}
}
