// This file is automatically generated by Kumquat.
// Do not modify this file - YOUR CHANGES WILL BE ERASED!

using Lime;

namespace Game.Scenes.Data;
public class AlertDialog : AlertDialog<Lime.Frame>
{
	public const string AssetPath = "Shell/AlertDialog";

	public static readonly Lime.Frame FrameCache = (Lime.Frame)Node.Load(AssetPath);

	public AlertDialog() : base(FrameCache.Clone<Node>()) { }

	public AlertDialog(Node node) : base(node) { }

	public new AlertDialog Clone()
	{
		return new AlertDialog(It.Clone<Node>());
	}
}

public class AlertDialog<T> : ParsedNode where T : Node
{
	public T It => (T)Node;


	public class Title : ParsedNode
	{
		public Lime.RichText It => (Lime.RichText)Node;

		public Title(Node node)
		{
			Node = node;
		}

		public Title Clone()
		{
			return new Title(It.Clone<Node>());
		}
	}

	public readonly Title @_Title;
	public readonly BtnOk<Lime.Button> @_BtnOk;

	public AlertDialog() : this(AlertDialog.FrameCache.Clone<Node>()) { }
	public AlertDialog(Node node)
	{
		Node = node;
		@_Title = new Title(Node.Find<Node>("@Title"));
		@_BtnOk = new BtnOk<Lime.Button>(Node.Find<Node>("@BtnOk"));
	}

	public AlertDialog<T> Clone()
	{
		return new AlertDialog<T>(It.Clone<Node>());
	}

	public T RunAnimationHide()
	{
		Node.RunAnimation("Hide");
		return (T)Node;
	}
	public T RunAnimationShow()
	{
		Node.RunAnimation("Show");
		return (T)Node;
	}
}
