// This file is automatically generated by Kumquat.
// Do not modify this file - YOUR CHANGES WILL BE ERASED!

using Lime;

namespace Game.Scenes.Data;
public class BtnX : BtnX<Lime.Frame>
{
	public const string AssetPath = "Shell/Externals/BtnX";

	public static readonly Lime.Frame FrameCache = (Lime.Frame)Node.Load(AssetPath);

	public BtnX() : base(FrameCache.Clone<Node>()) { }

	public BtnX(Node node) : base(node) { }

	public new BtnX Clone()
	{
		return new BtnX(It.Clone<Node>());
	}
}

public class BtnX<T> : ParsedNode where T : Node
{
	public T It => (T)Node;



	public BtnX() : this(BtnX.FrameCache.Clone<Node>()) { }

	public BtnX(Node node)
	{
		Node = node;
	}

	public BtnX<T> Clone()
	{
		return new BtnX<T>(It.Clone<Node>());
	}

	public T RunAnimationInit()
	{
		Node.RunAnimation("Init");
		return (T)Node;
	}
	public T RunAnimationNormal()
	{
		Node.RunAnimation("Normal");
		return (T)Node;
	}
	public T RunAnimationFocus()
	{
		Node.RunAnimation("Focus");
		return (T)Node;
	}
	public T RunAnimationPress()
	{
		Node.RunAnimation("Press");
		return (T)Node;
	}
	public T RunAnimationRelease()
	{
		Node.RunAnimation("Release");
		return (T)Node;
	}
	public T RunAnimationDisable()
	{
		Node.RunAnimation("Disable");
		return (T)Node;
	}
}
