// This file is automatically generated by Kumquat.
// Do not modify this file - YOUR CHANGES WILL BE ERASED!

using Lime;

namespace Game.Scenes.Data;
public class DarkScreen : DarkScreen<Lime.Frame>
{
	public const string AssetPath = "Shell/DarkScreen";

	public static readonly Lime.Frame FrameCache = (Lime.Frame)Node.Load(AssetPath);

	public DarkScreen() : base(FrameCache.Clone<Node>()) { }

	public DarkScreen(Node node) : base(node) { }

	public new DarkScreen Clone()
	{
		return new DarkScreen(It.Clone<Node>());
	}
}

public class DarkScreen<T> : ParsedNode where T : Node
{
	public T It => (T)Node;



	public DarkScreen() : this(DarkScreen.FrameCache.Clone<Node>()) { }

	public DarkScreen(Node node)
	{
		Node = node;
	}

	public DarkScreen<T> Clone()
	{
		return new DarkScreen<T>(It.Clone<Node>());
	}

	public T RunAnimationBlackout()
	{
		Node.RunAnimation("Blackout");
		return (T)Node;
	}
	public T RunAnimationLightout()
	{
		Node.RunAnimation("Lightout");
		return (T)Node;
	}
}
