// This file is automatically generated by Kumquat.
// Do not modify this file - YOUR CHANGES WILL BE ERASED!

using Lime;

namespace Game.Scenes.Data;
public class Splash : Splash<Lime.Frame>
{
	public const string AssetPath = "Shell/Splash";

	public static readonly Lime.Frame FrameCache = (Lime.Frame)Node.Load(AssetPath);

	public Splash() : base(FrameCache.Clone<Node>()) { }

	public Splash(Node node) : base(node) { }

	public new Splash Clone()
	{
		return new Splash(It.Clone<Node>());
	}
}

public class Splash<T> : ParsedNode where T : Node
{
	public T It => (T)Node;



	public Splash() : this(Splash.FrameCache.Clone<Node>()) { }

	public Splash(Node node)
	{
		Node = node;
	}

	public Splash<T> Clone()
	{
		return new Splash<T>(It.Clone<Node>());
	}

	public T RunAnimationStart()
	{
		Node.RunAnimation("Start");
		return (T)Node;
	}
	public T RunAnimationDone()
	{
		Node.RunAnimation("Done");
		return (T)Node;
	}
}
