// This file isn't generated, but this comment is necessary to exclude it from analysis.
// <auto-generated/>

namespace QualityAssurance.RemoteScriptingClientScripts
{
	internal static class ScriptsPreserve
	{
		[System.AttributeUsage(System.AttributeTargets.All)]
		private sealed class PreserveAttribute : System.Attribute
		{
			public bool AllMembers;
			public bool Conditional;
		}

		[Preserve]
		private static void SkipCodeFromBeingLinked()
		{
			System.Text.RegularExpressions.Regex.IsMatch(null, null);
			string.Empty.Replace(string.Empty, string.Empty, System.StringComparison.Ordinal);
			string.Empty.IndexOf(string.Empty, System.StringComparison.Ordinal);
			string.Empty.IndexOf('\0', System.StringComparison.Ordinal);
			string.Empty.StartsWith(string.Empty, System.StringComparison.Ordinal);
			string.Empty.Contains(string.Empty, System.StringComparison.Ordinal);
		}
	}
}
